[package]
name = "lepa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
inkwell = { git = "https://github.com/Faouzi1406/inkwell.git", features = ["llvm12-0"] }
rand = "0.8.5"
